# yamllint disable rule:comments-indentation
---
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: dark #light/dark
jwt_secret: apNZSyGTywQFx3wVR7smQ2Jaz #any text or number you want to add here to create jwt Token

default_redirection_url: https://google.com/ #where to redirect for a non-existent URL

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  read_buffer_size: 4096
  write_buffer_size: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log:
  level: debug

totp:
  issuer: example.com #your authelia top-level domain
  period: 30
  skew: 1

authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml #this is where your authorized users are stored 
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain:
        - "auth.example.com"
      policy: bypass
    - domain: # Proxies only requiring username and password
        - "portainer.example.com"
      policy: one_factor
    - domain: # Proxies only requiring username and password
        - "whoogle.example.com"
      policy: one_factor
    - domain: # Proxies only requiring username and password
        - "shorturl.example.com"
      policy: one_factor
    - domain: # Proxies only requiring username and password
        - "uptime.example.com"
      policy: one_factor
    - domain: # Proxies only requiring username and password
        - "raneto.example.com"
      policy: one_factor
    - domain: # Proxies only requiring username and password
        - "docs.example.com"
      policy: one_factor
    - domain: # Proxies only requiring username and password
        - "dashboard.example.com"
      policy: one_factor
    - domain: # Proxies only requiring username and password
        - "organizer.example.com"
      policy: one_factor
    - domain: # Proxies only requiring username and password
        - "flame.example.com"
      policy: one_factor
    - domain: # Proxies only requiring username and password
        - "webtop.example.com"
      policy: one_factor
    - domain: # Proxies only requiring username and password
        - "speedtest.example.com"
      policy: one_factor
    - domain: # Proxies only requiring username and password
        - "scrutiny.example.com"
      policy: one_factor
    - domain: # Proxies only requiring username and password
        - "rss.example.com"
      policy: one_factor
    - domain: # Proxies only requiring username and password
        - "dozzle.example.com"
      policy: one_factor
    - domain: # Proxies only requiring username and password
        - "wiki.example.com"
      policy: one_factor
    - domain: # Proxies only requiring username and password
        - "social.example.com"
      policy: one_factor
#     networks:
#       - 192.168.14.0/24
    - domain: # Proxies needing 2 factor below
        - "nextcloud.example.com"
      policy: two_factor
#     networks:
#        - 192.168.14.0/24
         

session:
  name: authelia_session
  secret: unsecure_session_secret #any text or number you want to add here to create jwt Token
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: example.com  # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  local:
    path: /config/db.sqlite3 #this is your databse. You could use a mysql database if you want.
  encryption_key: D9ZZLjcFMuL5AVUKJ4EaCfB26 
  
notifier:
  disable_startup_check: true #true/false
  smtp:
    username: example@live.com #your email address
    password: password! #your email password
    host: smtp-mail.outlook.com #email smtp server
    port: 587 #email smtp port
    sender: example@live.com
    identifier: localhost
    subject: "[Authelia] {title}" #email subject
    startup_check_address: example@live.com
    disable_require_tls: false
    disable_html_emails: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2
...

